# Generated by Django 4.0.1 on 2023-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_user_is_active_user_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ME', 'Mentee'), ('MO', 'Mentor')], default='ME', max_length=2),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('skills', models.ManyToManyField(to='prototype.Skill')),
            ],
        ),
    ]
