# Generated by Django 4.0.1 on 2023-04-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0006_remove_notification_email_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='skills',
        ),
    ]
